---
- hosts: all
  become: true
  tasks:
    - name: Instalar Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Iniciar y habilitar Nginx
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Configurar Nginx como Load Balancer
      copy:
        content: |
          upstream backend {
              server 192.168.33.10;  # IP del servidor Apache 1
              server 192.168.33.11;  # IP del servidor Apache 2
          }

          server {
              listen 80;

              location / {
                  proxy_pass http://backend;
              }
          }
        dest: /etc/nginx/conf.d/load_balancer.conf

    - name: Reiniciar Nginx
      service:
        name: nginx
        state: restarted
