---
- hosts: all
  become: true
  tasks:
    - name: Instalar Apache
      apt:
        name: apache2
        state: present
        update_cache: yes

    - name: Iniciar y habilitar Apache
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Copiar archivo de prueba
      copy:
        content: "<h1>Hola desde Apache</h1>"
        dest: /var/www/html/index.html

  - name: Configurar locale a UTF-8
    locale_gen:
      name: "en_US.UTF-8"
      state: present

  - name: Establecer locale
    lineinfile:
      path: /etc/default/locale
      line: "LANG=en_US.UTF-8"

